/*
 * DriverScorecard — Phase 58.
 *
 * Per-driver weekly scorecard. Mirrors HaulerScorecard (Phase 49) but
 * at driver granularity. Renders chrome-less (App.jsx routes it OUTSIDE
 * Shell) so the on-screen view is exactly what gets rasterised on print.
 *
 * Sections, top to bottom:
 *   - PrintBar (.no-print)
 *   - Letterhead (AXIS · driver · period · generated by)
 *   - Verdict callout (top_tier / in_band / watch / attention)
 *   - Week KPIs (trips · tonnes · on-time · hours)
 *   - Safety score trend (8 weeks)
 *   - Coaching attended this week
 *   - Footer
 */

import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { authFetch } from '../lib/auth';

const VERDICT_LABEL = {
  top_tier:  'Top tier',
  in_band:   'In band',
  watch:     'Watch · monitoring',
  attention: 'Attention required',
};
const VERDICT_TONE = {
  top_tier:  'var(--signal-green)',
  in_band:   'var(--text)',
  watch:     'var(--signal-amber)',
  attention: 'var(--bauxite-rust)',
};
const REST_LABEL = { compliant: 'Compliant', warning: 'Warning', breach: 'Breach' };
const REST_TONE  = { compliant: 'var(--signal-green)', warning: 'var(--signal-amber)', breach: 'var(--bauxite-rust)' };
const SHIFT_LABEL = { day: 'Day', night: 'Night', rest: 'Rest day', relief: 'Relief pool' };

export default function DriverScorecard() {
  const { id } = useParams();
  const [data, setData]   = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    document.title = `AXIS · Driver scorecard · ${id}`;
    document.body.classList.add('digest-mode');
    return () => document.body.classList.remove('digest-mode');
  }, [id]);

  useEffect(() => {
    let abort = false;
    authFetch(`/api/drivers/${id}/scorecard`)
      .then((r) => r.ok ? r.json() : r.json().then((j) => Promise.reject(new Error(j.error || `HTTP ${r.status}`))))
      .then((j) => { if (!abort) setData(j); })
      .catch((err) => { if (!abort) setError(err.message); });
    return () => { abort = true; };
  }, [id]);

  if (error) return <Frame><p style={{ color: 'var(--bauxite-rust)' }}>{error}</p></Frame>;
  if (!data) return <Frame><p style={{ color: 'var(--text-tertiary)' }}>Composing scorecard…</p></Frame>;

  return (
    <Frame>
      <PrintBar />
      <Letterhead data={data} />
      <VerdictBanner verdict={data.verdict} restStatus={data.safety.rest_status} />
      <WeekKPIs week={data.week} />
      <SafetyBlock safety={data.safety} />
      <CoachingBlock coaching={data.coaching} />
      <Footer data={data} />
    </Frame>
  );
}

// ── Layout ────────────────────────────────────────────────────────

function Frame({ children }) {
  return (
    <div style={{
      maxWidth: 760,
      margin: '0 auto',
      padding: '32px 36px 64px',
      background: '#fff',
      minHeight: '100vh',
      color: 'var(--text)',
      fontFamily: 'var(--font-primary)',
    }}>
      {children}
    </div>
  );
}

function PrintBar() {
  return (
    <div className="no-print" style={{
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      marginBottom: 24, padding: '8px 12px',
      background: 'var(--surface)', borderRadius: 'var(--radius-sm)',
      fontSize: 'var(--ts-caption-size)', color: 'var(--text-secondary)',
    }}>
      <span>Cmd-P / Ctrl-P to save as PDF</span>
      <button
        type="button"
        onClick={() => window.print()}
        style={{
          padding: '4px 12px',
          background: 'var(--bauxite-rust)', color: 'var(--bone)',
          border: 'none', borderRadius: 'var(--radius-sm)',
          fontSize: 'var(--ts-caption-size)', cursor: 'pointer',
          fontFamily: 'inherit',
        }}
      >Print</button>
    </div>
  );
}

function Letterhead({ data }) {
  const generatedAt = new Date(data.generated_at).toLocaleString('en-GB', {
    timeZone: 'UTC',
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: false,
  });
  const periodStart = new Date(data.period.since).toLocaleDateString('en-GB',
    { day: '2-digit', month: 'long' });
  const periodEnd   = new Date(data.period.until).toLocaleDateString('en-GB',
    { day: '2-digit', month: 'long', year: 'numeric' });
  return (
    <header style={{ marginBottom: 24, paddingBottom: 18, borderBottom: '2px solid var(--bauxite-rust)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 24 }}>
        <div>
          <div className="eyebrow" style={{ color: 'var(--bauxite-rust)', marginBottom: 4 }}>
            AXIS · Driver weekly scorecard
          </div>
          <h1 style={{
            margin: 0, fontSize: 32,
            fontWeight: 'var(--fw-medium)',
            color: 'var(--text)', letterSpacing: '-0.01em',
          }}>
            {data.driver.full_name}
          </h1>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', marginTop: 4 }}>
            <span className="mono">{data.driver.licence_number}</span>
            {' · '}{data.driver.hauler_display}
            {' · '}{SHIFT_LABEL[data.driver.shift] ?? data.driver.shift}
            {' · '}{data.driver.years_experience} yrs experience
            {data.driver.assigned_plate && (
              <>{' · '}<span className="mono">{data.driver.assigned_plate}</span></>
            )}
          </div>
        </div>
        <div style={{ textAlign: 'right', fontSize: 11, color: 'var(--text-tertiary)' }}>
          <div className="mono" style={{ letterSpacing: '0.06em' }}>WEEK OF</div>
          <div style={{ fontSize: 14, color: 'var(--text)', fontWeight: 'var(--fw-medium)', marginTop: 2 }}>
            {periodStart} → {periodEnd}
          </div>
          {data.generated_by && (
            <div style={{ marginTop: 8 }}>
              Generated by <strong>{data.generated_by.display_name}</strong>
              <br />{data.generated_by.organisation}
              <br />at {generatedAt} UTC
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

function VerdictBanner({ verdict, restStatus }) {
  const tone = VERDICT_TONE[verdict] ?? 'var(--text)';
  return (
    <section style={{
      marginBottom: 22,
      padding: 'var(--space-4)',
      background: tone === 'var(--signal-green)' ? 'rgba(46, 107, 63, 0.06)'
                : tone === 'var(--bauxite-rust)' ? 'rgba(162, 62, 35, 0.06)'
                : tone === 'var(--signal-amber)' ? 'rgba(217, 158, 55, 0.08)'
                : 'var(--surface)',
      borderRadius: 'var(--radius-md)',
      borderLeft: `4px solid ${tone}`,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'baseline',
    }}>
      <div>
        <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 4 }}>Verdict</div>
        <div style={{
          fontSize: 22, fontWeight: 'var(--fw-medium)',
          color: tone, lineHeight: 1.05,
        }}>
          {VERDICT_LABEL[verdict] ?? '—'}
        </div>
      </div>
      <div style={{ textAlign: 'right' }}>
        <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 4 }}>Rest status</div>
        <div style={{
          fontSize: 16, fontWeight: 'var(--fw-medium)',
          color: REST_TONE[restStatus] ?? 'var(--text)',
        }}>
          {REST_LABEL[restStatus] ?? restStatus}
        </div>
      </div>
    </section>
  );
}

function Section({ title, children, sub }) {
  return (
    <section style={{ marginBottom: 22, breakInside: 'avoid' }}>
      <h2 style={{
        margin: 0, marginBottom: 8, paddingBottom: 4,
        fontSize: 11, letterSpacing: '0.18em', textTransform: 'uppercase',
        color: 'var(--bauxite-rust)',
        borderBottom: '1px solid var(--border-hairline)',
        fontWeight: 500,
      }}>{title}</h2>
      {sub && (
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 8 }}>
          {sub}
        </div>
      )}
      {children}
    </section>
  );
}

function WeekKPIs({ week }) {
  return (
    <Section title="Week in numbers">
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12 }}>
        <Kpi label="Trips" value={week.trips} sub={`${week.laden_trips} laden · ${week.delayed} delayed`} />
        <Kpi label="Tonnes" value={week.tonnes.toLocaleString()} sub="laden tonnage" />
        <Kpi label="On-time" value={week.on_time_pct != null ? `${week.on_time_pct.toFixed(1)}%` : '—'}
             sub={week.delayed > 0 ? `${week.delayed} delayed` : 'clean'}
             tone={week.on_time_pct != null && week.on_time_pct < 90 ? 'amber' : null} />
        <Kpi label="Hours / wk" value={`${week.hours.toFixed(1)} h`}
             sub={week.harsh_events > 0 ? `${week.harsh_events} harsh events` : 'no harsh events'}
             tone={week.hours > 56 ? 'rust' : week.hours > 48 ? 'amber' : null} />
      </div>
    </Section>
  );
}

function Kpi({ label, value, sub, tone }) {
  const color = tone === 'rust'  ? 'var(--bauxite-rust)'
              : tone === 'green' ? 'var(--signal-green)'
              : tone === 'amber' ? 'var(--signal-amber)'
              : 'var(--text)';
  return (
    <div style={{
      padding: '10px 12px',
      background: 'var(--surface)',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid var(--border-hairline)',
    }}>
      <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 4 }}>{label}</div>
      <div className="tabular" style={{
        fontSize: 22, lineHeight: 1.05, fontWeight: 'var(--fw-medium)', color,
      }}>{value}</div>
      {sub && (
        <div style={{ fontSize: 10, color: 'var(--text-tertiary)', marginTop: 4 }}>{sub}</div>
      )}
    </div>
  );
}

function SafetyBlock({ safety }) {
  const series = safety.series ?? [];
  const max = Math.max(100, ...series.map((p) => p.score));
  const min = Math.min(...series.map((p) => p.score), 60);
  const span = Math.max(1, max - min);
  const trendTone = safety.trend_delta > 0 ? 'var(--signal-green)'
                  : safety.trend_delta < 0 ? 'var(--bauxite-rust)'
                  : 'var(--text-tertiary)';
  return (
    <Section title="Safety score · 8 weeks"
             sub={`Current ${safety.score} · ${safety.trend_delta >= 0 ? '+' : ''}${safety.trend_delta} pts over last 4 weeks`}>
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${series.length}, 1fr)`,
        gap: 6,
        alignItems: 'flex-end',
        height: 80,
        marginBottom: 4,
      }}>
        {series.map((p, i) => {
          const isCurrent = i === series.length - 1;
          const ratio = (p.score - min) / span;
          const height = 12 + Math.round(ratio * 56);
          return (
            <div key={i} style={{
              display: 'flex', flexDirection: 'column',
              alignItems: 'center', gap: 4,
            }}>
              <span className="tabular" style={{ fontSize: 9, color: 'var(--text-tertiary)' }}>
                {p.score}
              </span>
              <div style={{
                width: '100%',
                height,
                background: isCurrent ? 'var(--bauxite-rust)' : 'var(--border-soft)',
                borderRadius: 2,
              }} />
            </div>
          );
        })}
      </div>
      <div style={{
        fontSize: 11,
        color: trendTone,
        textAlign: 'right',
        fontWeight: 'var(--fw-medium)',
      }}>
        {safety.trend_delta >= 0 ? '↑' : '↓'} trend {safety.trend_delta >= 0 ? '+' : ''}{safety.trend_delta} pts
      </div>
    </Section>
  );
}

function CoachingBlock({ coaching }) {
  return (
    <Section title="Coaching attended · this week">
      {coaching.length === 0 ? (
        <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic', fontSize: 12 }}>
          No coaching sessions attended in the window.
        </p>
      ) : (
        <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
          {coaching.map((c) => (
            <li key={c.id} style={{
              padding: '8px 12px',
              background: 'var(--surface)',
              borderRadius: 'var(--radius-sm)',
              border: '1px solid var(--border-hairline)',
              fontSize: 12,
            }}>
              <div style={{
                display: 'flex', justifyContent: 'space-between',
                alignItems: 'baseline', gap: 8,
              }}>
                <strong style={{ color: 'var(--text)' }}>{c.topic}</strong>
                <span className="mono" style={{ fontSize: 10, color: 'var(--text-tertiary)' }}>
                  {new Date(c.held_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })}
                </span>
              </div>
              <div style={{ color: 'var(--text-secondary)', marginTop: 4 }}>
                w/ {c.dispatcher_name}
                {c.expected_delta_pct != null && (
                  <> · expected {c.expected_delta_pct > 0 ? '+' : ''}{c.expected_delta_pct}% hold-rate delta</>
                )}
              </div>
            </li>
          ))}
        </ul>
      )}
    </Section>
  );
}

function Footer({ data }) {
  return (
    <footer style={{
      marginTop: 32, paddingTop: 12,
      borderTop: '1px solid var(--border-hairline)',
      fontSize: 10, color: 'var(--text-tertiary)',
      display: 'flex', justifyContent: 'space-between',
    }}>
      <span>AXIS Command Center · NewCo Logistics JV Ltd. · Nyinahin–Takoradi corridor</span>
      <span className="mono">scorecard · {data.driver.id} · {data.generated_at.slice(0, 19).replace('T', ' ')}Z</span>
    </footer>
  );
}
