/*
 * HaulerScorecard — Phase 49.
 *
 * Per-hauler weekly scorecard. Mirrors TodayDigest (Phase 40) but at
 * hauler granularity and on a weekly cadence. Renders chrome-less
 * (App.jsx routes it OUTSIDE Shell) so the on-screen view is exactly
 * what gets rasterised on print.
 *
 * Sections, top to bottom:
 *   - PrintBar (.no-print)
 *   - Letterhead (AXIS · hauler · period · generated by)
 *   - Week KPIs (trips · tonnes · margin · on-time)
 *   - Daily tonnage chart (7 bars + delayed markers)
 *   - Month-end forecast (this hauler's slice + corridor rank)
 *   - Lifecycle activity in window (HSE / coaching / licences)
 *   - Audit trail tail (lender-blanked)
 *   - Footer (doc id, contact)
 */

import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { authFetch } from '../lib/auth';

const VERDICT_LABEL = {
  on_pace:           'On pace',
  drift:             'Drift · within tolerance',
  lagging:           'Lagging',
  severely_lagging:  'Severely lagging',
};
const VERDICT_TONE = {
  on_pace:           'var(--signal-green)',
  drift:             'var(--text)',
  lagging:           'var(--signal-amber)',
  severely_lagging:  'var(--bauxite-rust)',
};

export default function HaulerScorecard() {
  const { id } = useParams();
  const [data, setData]   = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    document.title = `AXIS · Hauler scorecard · ${id}`;
    document.body.classList.add('digest-mode');
    return () => document.body.classList.remove('digest-mode');
  }, [id]);

  useEffect(() => {
    let abort = false;
    authFetch(`/api/haulers/${id}/scorecard`)
      .then((r) => (r.ok ? r.json() : r.json().then((j) => Promise.reject(new Error(j.error || `HTTP ${r.status}`)))))
      .then((j) => { if (!abort) setData(j); })
      .catch((err) => { if (!abort) setError(err.message); });
    return () => { abort = true; };
  }, [id]);

  if (error) return <Frame><p style={{ color: 'var(--bauxite-rust)' }}>{error}</p></Frame>;
  if (!data) return <Frame><p style={{ color: 'var(--text-tertiary)' }}>Composing scorecard…</p></Frame>;

  return (
    <Frame>
      <PrintBar />
      <Letterhead data={data} />
      <WeekKPIs week={data.week} />
      <DailyTonnage daily={data.week.daily} />
      {data.forecast && (
        <ForecastBlock forecast={data.forecast} rank={data.corridor_rank} />
      )}
      <LifecycleBlock lifecycle={data.lifecycle} period={data.period} />
      <AuditBlock audit={data.audit} />
      <Footer data={data} />
    </Frame>
  );
}

// ── Layout ────────────────────────────────────────────────────────

function Frame({ children }) {
  return (
    <div style={{
      maxWidth: 820,
      margin: '0 auto',
      padding: '32px 36px 64px',
      background: '#fff',
      minHeight: '100vh',
      color: 'var(--text)',
      fontFamily: 'var(--font-primary)',
    }}>
      {children}
    </div>
  );
}

function PrintBar() {
  return (
    <div className="no-print" style={{
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
      padding: '8px 12px',
      background: 'var(--surface)',
      borderRadius: 'var(--radius-sm)',
      fontSize: 'var(--ts-caption-size)',
      color: 'var(--text-secondary)',
    }}>
      <span>Cmd-P / Ctrl-P to save as PDF</span>
      <button
        type="button"
        onClick={() => window.print()}
        style={{
          padding: '4px 12px',
          background: 'var(--bauxite-rust)',
          color: 'var(--bone)',
          border: 'none',
          borderRadius: 'var(--radius-sm)',
          fontSize: 'var(--ts-caption-size)',
          cursor: 'pointer',
          fontFamily: 'inherit',
        }}
      >
        Print
      </button>
    </div>
  );
}

function Letterhead({ data }) {
  const generatedAt = new Date(data.generated_at).toLocaleString('en-GB', {
    timeZone: 'UTC',
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: false,
  });
  const periodStart = new Date(data.period.since).toLocaleDateString('en-GB',
    { day: '2-digit', month: 'long' });
  const periodEnd   = new Date(data.period.until).toLocaleDateString('en-GB',
    { day: '2-digit', month: 'long', year: 'numeric' });
  return (
    <header style={{ marginBottom: 28, paddingBottom: 18, borderBottom: '2px solid var(--bauxite-rust)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 24 }}>
        <div>
          <div className="eyebrow" style={{ color: 'var(--bauxite-rust)', marginBottom: 4 }}>
            AXIS · Hauler weekly scorecard
          </div>
          <h1 style={{
            margin: 0,
            fontSize: 32,
            fontWeight: 'var(--fw-medium)',
            color: 'var(--text)',
            letterSpacing: '-0.01em',
          }}>
            {data.hauler.display_name}
          </h1>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', marginTop: 4 }}>
            {data.hauler.id} · {data.hauler.contracted_trucks} contracted /{' '}
            {data.hauler.active_trucks} active · onboarded {data.hauler.onboarded_date}
          </div>
        </div>
        <div style={{ textAlign: 'right', fontSize: 11, color: 'var(--text-tertiary)' }}>
          <div className="mono" style={{ letterSpacing: '0.06em' }}>WEEK OF</div>
          <div style={{ fontSize: 14, color: 'var(--text)', fontWeight: 'var(--fw-medium)', marginTop: 2 }}>
            {periodStart} → {periodEnd}
          </div>
          {data.generated_by && (
            <div style={{ marginTop: 8 }}>
              Generated by <strong>{data.generated_by.display_name}</strong>
              <br />{data.generated_by.organisation}
              <br />at {generatedAt} UTC
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// ── Sections ──────────────────────────────────────────────────────

function Section({ title, children, sub }) {
  return (
    <section style={{ marginBottom: 22, breakInside: 'avoid' }}>
      <h2 style={{
        margin: 0, marginBottom: 8, paddingBottom: 4,
        fontSize: 11, letterSpacing: '0.18em', textTransform: 'uppercase',
        color: 'var(--bauxite-rust)',
        borderBottom: '1px solid var(--border-hairline)',
        fontWeight: 500,
      }}>
        {title}
      </h2>
      {sub && (
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 8 }}>
          {sub}
        </div>
      )}
      {children}
    </section>
  );
}

function WeekKPIs({ week }) {
  return (
    <Section title="Week in numbers">
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
        gap: 12,
      }}>
        <Kpi
          label="Trips delivered"
          value={week.trips}
          sub={`${week.laden_trips} laden · ${week.delayed} delayed`}
        />
        <Kpi
          label="Tonnes (laden)"
          value={`${(week.tonnes / 1000).toFixed(1)} kt`}
          sub={week.tonnes.toLocaleString() + ' t'}
        />
        <Kpi
          label="Margin"
          value={`$${week.margin_usd.toLocaleString()}`}
          sub={`rev $${week.revenue_usd.toLocaleString()} · cost $${week.cost_usd.toLocaleString()}`}
          tone={week.margin_usd >= 0 ? null : 'rust'}
        />
        <Kpi
          label="On-time"
          value={week.on_time_pct != null ? `${week.on_time_pct.toFixed(1)}%` : '—'}
          sub={week.delayed > 0 ? `${week.delayed} delayed` : 'clean week'}
          tone={week.on_time_pct != null && week.on_time_pct < 90 ? 'amber' : (week.on_time_pct === 100 ? 'green' : null)}
        />
      </div>
    </Section>
  );
}

function Kpi({ label, value, sub, tone }) {
  const color = tone === 'rust'  ? 'var(--bauxite-rust)'
              : tone === 'green' ? 'var(--signal-green)'
              : tone === 'amber' ? 'var(--signal-amber)'
              : 'var(--text)';
  return (
    <div style={{
      padding: '10px 12px',
      background: 'var(--surface)',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid var(--border-hairline)',
    }}>
      <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 4 }}>{label}</div>
      <div className="tabular" style={{
        fontSize: 22, lineHeight: 1.05, fontWeight: 'var(--fw-medium)', color,
      }}>{value}</div>
      {sub && (
        <div style={{ fontSize: 10, color: 'var(--text-tertiary)', marginTop: 4 }}>
          {sub}
        </div>
      )}
    </div>
  );
}

function DailyTonnage({ daily }) {
  const max = Math.max(1, ...daily.map((d) => d.tonnes));
  return (
    <Section title="Daily tonnage" sub="Bar height = tonnes laden delivered. Empty bar = no laden trips that day.">
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${daily.length}, 1fr)`,
        gap: 6,
        alignItems: 'flex-end',
        height: 80,
        marginBottom: 4,
      }}>
        {daily.map((d) => {
          const pct = (d.tonnes / max) * 100;
          return (
            <div key={d.date} style={{
              display: 'flex', flexDirection: 'column', alignItems: 'center',
              height: '100%', justifyContent: 'flex-end',
            }}>
              <span className="tabular" style={{ fontSize: 9, color: 'var(--text-tertiary)' }}>
                {d.tonnes > 0 ? d.tonnes : '—'}
              </span>
              <div style={{
                width: '100%',
                height: `${Math.max(2, pct)}%`,
                background: d.delayed > 0 ? 'var(--signal-amber)' : 'var(--bauxite-rust)',
                opacity: d.tonnes > 0 ? 1 : 0.15,
                borderRadius: 2,
                marginTop: 2,
              }} />
            </div>
          );
        })}
      </div>
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${daily.length}, 1fr)`,
        gap: 6,
        fontSize: 10, color: 'var(--text-tertiary)', textAlign: 'center',
      }}>
        {daily.map((d) => (
          <span key={d.date} className="mono">
            {new Date(d.date).toLocaleDateString('en-GB', { weekday: 'short' }).slice(0, 2)}
          </span>
        ))}
      </div>
    </Section>
  );
}

function ForecastBlock({ forecast, rank }) {
  const tone = VERDICT_TONE[forecast.verdict] ?? 'var(--text)';
  const verdictLabel = VERDICT_LABEL[forecast.verdict] ?? '—';
  const shortfall = Math.max(0, forecast.contracted_monthly - forecast.projected_eom);
  return (
    <Section title="Month-end forecast">
      <div style={{
        display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12,
        marginBottom: 8,
      }}>
        <Kpi
          label="Projected EOM"
          value={`${(forecast.projected_eom / 1000).toFixed(1)} kt`}
          sub={`vs ${(forecast.contracted_monthly / 1000).toFixed(1)} kt contracted`}
          tone={forecast.verdict === 'severely_lagging' ? 'rust'
              : forecast.verdict === 'lagging' ? 'amber'
              : forecast.verdict === 'on_pace' ? 'green' : null}
        />
        <Kpi
          label="Run rate"
          value={`${forecast.projected_pct_contracted.toFixed(0)}%`}
          sub={verdictLabel}
          tone={forecast.verdict === 'severely_lagging' ? 'rust'
              : forecast.verdict === 'lagging' ? 'amber' : null}
        />
        <Kpi
          label="Corridor rank"
          value={rank ? `#${rank.rank} / ${rank.of}` : '—'}
          sub="among active haulers"
        />
      </div>
      {shortfall > 0 && (
        <div style={{
          padding: '8px 12px', borderRadius: 'var(--radius-sm)',
          background: tone === 'var(--bauxite-rust)' ? 'rgba(162,62,35,0.06)' : 'var(--surface)',
          fontSize: 12, color: 'var(--text-secondary)',
        }}>
          To clear contracted target this month, deliver an additional{' '}
          <strong style={{ color: tone }}>{(shortfall / 1000).toFixed(1)} kt</strong> over the
          remaining days.
        </div>
      )}
    </Section>
  );
}

function LifecycleBlock({ lifecycle }) {
  const items = [
    { label: 'HSE incidents logged', value: lifecycle.hse_logged, tone: lifecycle.hse_logged > 0 ? 'amber' : null },
    { label: 'HSE incidents closed', value: lifecycle.hse_closed, tone: 'green' },
    { label: 'Coaching sessions held', value: lifecycle.coaching_held },
    { label: 'Licences renewed', value: lifecycle.licences_renewed },
  ];
  const total = items.reduce((s, i) => s + i.value, 0);
  return (
    <Section title="Lifecycle activity · this week">
      {total === 0 ? (
        <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic', fontSize: 12 }}>
          No regulated lifecycle writes against this hauler in the window.
        </p>
      ) : (
        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12,
        }}>
          {items.map((i) => <Kpi key={i.label} label={i.label} value={i.value} tone={i.tone} />)}
        </div>
      )}
    </Section>
  );
}

function AuditBlock({ audit }) {
  if (audit?.restricted) {
    return (
      <Section title="Audit trail · this week">
        <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic', fontSize: 12 }}>
          Operational write history is restricted for the lender persona.
        </p>
      </Section>
    );
  }
  if (!audit?.recent?.length) {
    return (
      <Section title="Audit trail · this week">
        <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic', fontSize: 12 }}>
          No write activity affecting this hauler in the window.
        </p>
      </Section>
    );
  }
  return (
    <Section title={`Audit trail · ${audit.recent.length} write${audit.recent.length === 1 ? '' : 's'} this week`}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
        <thead>
          <tr style={{ color: 'var(--text-tertiary)', textAlign: 'left' }}>
            <th style={{ padding: '4px 8px' }}>Time</th>
            <th style={{ padding: '4px 8px' }}>Entity</th>
            <th style={{ padding: '4px 8px' }}>Action</th>
            <th style={{ padding: '4px 8px' }}>Summary</th>
            <th style={{ padding: '4px 8px' }}>Actor</th>
          </tr>
        </thead>
        <tbody>
          {audit.recent.map((r) => (
            <tr key={r.id} style={{ borderTop: '1px solid var(--border-hairline)', breakInside: 'avoid' }}>
              <td className="mono" style={{ padding: '4px 8px', color: 'var(--text-tertiary)' }}>
                {new Date(r.ts).toISOString().slice(5, 16).replace('T', ' ')}
              </td>
              <td className="mono" style={{ padding: '4px 8px', fontSize: 10, textTransform: 'uppercase' }}>
                {r.entity_type}
              </td>
              <td className="mono" style={{ padding: '4px 8px', fontSize: 10 }}>
                {r.action}
              </td>
              <td style={{ padding: '4px 8px' }}>{r.summary}</td>
              <td style={{ padding: '4px 8px', color: 'var(--text-secondary)' }}>{r.actor || '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </Section>
  );
}

function Footer({ data }) {
  return (
    <footer style={{
      marginTop: 32, paddingTop: 12,
      borderTop: '1px solid var(--border-hairline)',
      fontSize: 10, color: 'var(--text-tertiary)',
      display: 'flex', justifyContent: 'space-between',
    }}>
      <span>AXIS Command Center · NewCo Logistics JV Ltd. · Nyinahin–Takoradi corridor</span>
      <span className="mono">scorecard · {data.hauler.id} · {data.generated_at.slice(0, 19).replace('T', ' ')}Z</span>
    </footer>
  );
}
