/*
 * LenderPack — Phase 70.
 *
 * Print-friendly lender briefing pack. Mirrors the Phase 49
 * HaulerScorecard pattern: chrome-less route mounted OUTSIDE
 * Shell so what's on screen is exactly what rasterises on print.
 *
 * Composed server-side by services/lenderPack.js. The page renders
 * a single-document layout designed for PDF export via Cmd-P /
 * Ctrl-P:
 *
 *   - Letterhead (AXIS · period · generated by · headline status)
 *   - Executive summary (4 sentence narrative + counts)
 *   - DSCR block (current × target × series + computation breakdown)
 *   - Covenants table (every covenant + verdict + detail)
 *   - Capital + P&L block (debt/equity drawn, MTD, YTD)
 *   - Receivables ageing table (per band + chase counts)
 *   - Forecast block (verdict, trajectory, requirements)
 *   - Hauler ranking (every active hauler, attainment desc)
 *   - Open alerts (lender-relevant slice)
 *   - Footer (doc id, generation timestamp, contact)
 */

import { Fragment, useEffect, useState } from 'react';
import { authFetch } from '../lib/auth';

const STATUS_TONE = {
  PASS:   'var(--signal-green)',
  WATCH:  'var(--signal-amber)',
  BREACH: 'var(--bauxite-rust)',
};

const VERDICT_LABEL = {
  on_pace_or_above:    'On pace or above',
  below_floor_at_pace: 'Below floor at pace',
  severely_lagging:    'Severely lagging',
};

export default function LenderPack() {
  const [data, setData]   = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    document.title = 'AXIS · Lender briefing pack';
    document.body.classList.add('digest-mode');
    return () => document.body.classList.remove('digest-mode');
  }, []);

  useEffect(() => {
    let abort = false;
    authFetch('/api/lender/pack')
      .then((r) => (r.ok ? r.json() : r.json().then((j) => Promise.reject(new Error(j.error || `HTTP ${r.status}`)))))
      .then((j) => { if (!abort) setData(j); })
      .catch((err) => { if (!abort) setError(err.message); });
    return () => { abort = true; };
  }, []);

  if (error) return <Frame><p style={{ color: 'var(--bauxite-rust)' }}>{error}</p></Frame>;
  if (!data) return <Frame><p style={{ color: 'var(--text-tertiary)' }}>Composing lender pack…</p></Frame>;

  return (
    <Frame>
      <PrintBar />
      <Letterhead data={data} />
      <ExecSummary summary={data.executive_summary} period={data.period} />
      <DscrBlock dscr={data.dscr} />
      <CovenantsBlock covenants={data.covenants} />
      <CapitalAndPnlBlock capital={data.capital} pnl={data.pnl} />
      <ReceivablesBlock receivables={data.receivables} />
      <ForecastBlock forecast={data.forecast} />
      <HaulerRankingBlock haulers={data.hauler_ranking} />
      {data.risks && data.risks.length > 0 && (
        <RiskRegisterBlock risks={data.risks} counts={data.risk_counts} />
      )}
      {data.open_alerts.length > 0 && <OpenAlertsBlock alerts={data.open_alerts} />}
      <Footer data={data} />
    </Frame>
  );
}

// ── Layout ────────────────────────────────────────────────────────

function Frame({ children }) {
  return (
    <div style={{
      maxWidth: 820,
      margin: '0 auto',
      padding: '32px 36px 64px',
      background: '#fff',
      minHeight: '100vh',
      color: 'var(--text)',
      fontFamily: 'var(--font-primary)',
    }}>
      {children}
    </div>
  );
}

function PrintBar() {
  return (
    <div className="no-print" style={{
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
      padding: '8px 12px',
      background: 'var(--surface)',
      borderRadius: 'var(--radius-sm)',
      fontSize: 'var(--ts-caption-size)',
      color: 'var(--text-secondary)',
    }}>
      <span>Cmd-P / Ctrl-P to save as PDF</span>
      <button
        type="button"
        onClick={() => window.print()}
        style={{
          padding: '4px 12px',
          background: 'var(--bauxite-rust)',
          color: 'var(--bone)',
          border: 'none',
          borderRadius: 'var(--radius-sm)',
          fontSize: 'var(--ts-caption-size)',
          cursor: 'pointer',
          fontFamily: 'inherit',
        }}
      >
        Print
      </button>
    </div>
  );
}

function Letterhead({ data }) {
  const generatedAt = new Date(data.generated_at).toLocaleString('en-GB', {
    timeZone: 'UTC',
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: false,
  });
  const status = data.executive_summary.headline_status;
  return (
    <header style={{ marginBottom: 24, paddingBottom: 18, borderBottom: '2px solid var(--bauxite-rust)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 24 }}>
        <div>
          <div className="eyebrow" style={{ color: 'var(--bauxite-rust)', marginBottom: 4 }}>
            AXIS · Lender briefing pack
          </div>
          <h1 style={{
            margin: 0, fontSize: 32,
            fontWeight: 'var(--fw-medium)',
            color: 'var(--text)',
            letterSpacing: '-0.01em',
          }}>
            {data.corridor.name}
          </h1>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', marginTop: 4 }}>
            Offtaker {data.corridor.offtaker} · {data.corridor.contracted_trucks} contracted /{' '}
            {data.corridor.active_trucks} active · take-or-pay floor {data.corridor.take_or_pay_floor_pct}%
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div className="mono" style={{ fontSize: 11, color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>
            {data.period.label.toUpperCase()}
          </div>
          <div style={{
            fontSize: 14, color: 'var(--text)',
            fontWeight: 'var(--fw-medium)', marginTop: 2,
          }}>
            {data.period.month}
          </div>
          <span style={{
            display: 'inline-block', marginTop: 8,
            padding: '4px 10px',
            background: `color-mix(in srgb, ${STATUS_TONE[status]} 10%, transparent)`,
            border: `1px solid ${STATUS_TONE[status]}`,
            borderRadius: 999,
            fontSize: 11, letterSpacing: '0.08em',
            fontWeight: 'var(--fw-medium)',
            color: STATUS_TONE[status],
          }}>
            {status}
          </span>
          {data.generated_by && (
            <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-tertiary)' }}>
              Generated by <strong style={{ color: 'var(--text-secondary)' }}>{data.generated_by.display_name}</strong>
              <br />{data.generated_by.organisation}
              <br />at {generatedAt} UTC
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

function Section({ title, children, sub }) {
  return (
    <section style={{ marginBottom: 22, breakInside: 'avoid' }}>
      <h2 style={{
        margin: 0, marginBottom: 8, paddingBottom: 4,
        fontSize: 11, letterSpacing: '0.18em', textTransform: 'uppercase',
        color: 'var(--bauxite-rust)',
        borderBottom: '1px solid var(--border-hairline)',
        fontWeight: 500,
      }}>
        {title}
      </h2>
      {sub && (
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 8 }}>
          {sub}
        </div>
      )}
      {children}
    </section>
  );
}

// ── Sections ──────────────────────────────────────────────────────

function ExecSummary({ summary, period }) {
  const tone = STATUS_TONE[summary.headline_status];
  return (
    <Section title="Executive summary" sub={`Status as of ${new Date(period.end).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`}>
      <div style={{
        background: 'var(--surface)',
        borderLeft: `3px solid ${tone}`,
        padding: '12px 16px',
        borderRadius: 'var(--radius-sm)',
      }}>
        <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.6 }}>
          {summary.lines.map((line, i) => (
            <li key={i} style={{ fontSize: 13, color: 'var(--text)', marginBottom: 4 }}>
              {line}
            </li>
          ))}
        </ul>
      </div>
    </Section>
  );
}

function DscrBlock({ dscr }) {
  const tone = dscr.current >= dscr.target_min + 0.05 ? STATUS_TONE.PASS
             : dscr.current >= dscr.target_min        ? STATUS_TONE.WATCH
             :                                          STATUS_TONE.BREACH;
  return (
    <Section title="DSCR — debt service coverage">
      <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 24, alignItems: 'flex-start' }}>
        <div>
          <div className="tabular" style={{
            fontSize: 36, fontWeight: 'var(--fw-black)',
            color: tone, lineHeight: 1.05,
          }}>
            {dscr.current.toFixed(2)}×
          </div>
          <div className="micro" style={{ color: 'var(--text-tertiary)', marginTop: 4 }}>
            CURRENT (TRAILING 3M)
          </div>
        </div>
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.55 }}>
          <div style={{ marginBottom: 6 }}>
            <span style={{ color: 'var(--text-tertiary)' }}>Covenant floor</span>{' '}
            <span className="tabular" style={{ color: 'var(--text)', fontWeight: 'var(--fw-medium)' }}>{dscr.target_min.toFixed(2)}×</span>
            {' · '}
            <span style={{ color: 'var(--text-tertiary)' }}>Steady-state</span>{' '}
            <span className="tabular" style={{ color: 'var(--text)' }}>{dscr.steady_state.toFixed(2)}×</span>
            {' · '}
            <span style={{ color: 'var(--text-tertiary)' }}>Headroom</span>{' '}
            <span className="tabular" style={{ color: tone, fontWeight: 'var(--fw-medium)' }}>
              {dscr.headroom_pct >= 0 ? '+' : ''}{dscr.headroom_pct.toFixed(1)}%
            </span>
          </div>
          {dscr.computed && (
            <div style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>
              Live computation: ${dscr.computed.this_month_revenue_usd.toLocaleString()} forecast revenue
              − ${(dscr.computed.this_month_revenue_usd - dscr.computed.this_month_ebitda_usd).toLocaleString()} opcost ratio {(dscr.computed.opcost_ratio * 100).toFixed(1)}%
              = ${dscr.computed.this_month_ebitda_usd.toLocaleString()} EBITDA{' '}
              ÷ ${dscr.computed.monthly_debt_service_usd.toLocaleString()} monthly debt service.
            </div>
          )}
        </div>
      </div>

      {dscr.series && dscr.series.length > 0 && (
        <DscrSparkline series={dscr.series} target={dscr.target_min} />
      )}
    </Section>
  );
}

function DscrSparkline({ series, target }) {
  const max = Math.max(target * 1.4, ...series.map((s) => s.dscr || 0));
  return (
    <div style={{ marginTop: 12 }}>
      <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 6 }}>
        Last {series.length} months · floor at {target.toFixed(2)}×
      </div>
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${series.length}, 1fr)`,
        alignItems: 'flex-end',
        gap: 4,
        height: 56,
        position: 'relative',
      }}>
        {/* floor line */}
        <div style={{
          position: 'absolute',
          left: 0, right: 0,
          bottom: `${(target / max) * 100}%`,
          borderTop: '1px dashed var(--bauxite-rust)',
          opacity: 0.6,
        }} />
        {series.map((s, i) => {
          const v = s.dscr || 0;
          const heightPct = Math.max(4, (v / max) * 100);
          const tone = v >= target + 0.05 ? STATUS_TONE.PASS
                     : v >= target ? STATUS_TONE.WATCH
                     : STATUS_TONE.BREACH;
          return (
            <div key={i} style={{
              height: `${heightPct}%`,
              background: tone,
              opacity: s.partial ? 0.55 : 0.9,
              border: s.computed ? '1px solid var(--text)' : 'none',
              borderRadius: 1,
            }} title={`${s.month}: ${v.toFixed(2)}×${s.computed ? ' (live)' : ''}${s.partial ? ' (partial)' : ''}`} />
          );
        })}
      </div>
      <div style={{
        display: 'grid', gridTemplateColumns: `repeat(${series.length}, 1fr)`,
        gap: 4, marginTop: 4,
      }} className="mono tabular">
        {series.map((s, i) => (
          <div key={i} style={{ textAlign: 'center', fontSize: 9, color: 'var(--text-tertiary)' }}>
            {s.month?.slice(5) ?? ''}
          </div>
        ))}
      </div>
    </div>
  );
}

function CovenantsBlock({ covenants }) {
  return (
    <Section title="Covenant compliance" sub={`${covenants.length} covenants tested live against corridor state`}>
      <table style={{
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: 12,
      }}>
        <thead>
          <tr style={{ borderBottom: '1px solid var(--border-hairline)' }}>
            <th style={th}>Covenant</th>
            <th style={th}>Current</th>
            <th style={th}>Status</th>
            <th style={{ ...th, width: '50%' }}>Detail</th>
          </tr>
        </thead>
        <tbody>
          {covenants.map((c) => (
            <tr key={c.id} style={{ borderBottom: '1px solid var(--border-hairline)' }}>
              <td style={td}>{c.name}</td>
              <td style={{ ...td, fontFamily: 'var(--font-mono)', whiteSpace: 'nowrap' }}>{c.metric}</td>
              <td style={td}>
                <StatusPill status={c.status} />
              </td>
              <td style={{ ...td, color: 'var(--text-secondary)', fontSize: 11, lineHeight: 1.4 }}>
                {c.detail}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </Section>
  );
}

function StatusPill({ status }) {
  const tone = STATUS_TONE[status] || 'var(--text-secondary)';
  return (
    <span style={{
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: 999,
      background: `color-mix(in srgb, ${tone} 10%, transparent)`,
      border: `1px solid ${tone}`,
      color: tone,
      fontSize: 10,
      fontWeight: 'var(--fw-medium)',
      letterSpacing: '0.06em',
    }}>
      {status}
    </span>
  );
}

function CapitalAndPnlBlock({ capital, pnl }) {
  const debtPct  = capital.debt_committed_usd / (capital.debt_committed_usd + capital.equity_committed_usd) * 100;
  return (
    <Section title="Capital structure & P&L">
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <div>
          <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 6 }}>
            CAPITAL · {debtPct.toFixed(0)}/{(100 - debtPct).toFixed(0)} debt/equity
          </div>
          <KvRow label="Debt committed" value={`$${(capital.debt_committed_usd / 1e6).toFixed(1)}M`} />
          <KvRow label="Debt drawn"     value={`$${(capital.debt_drawn_usd / 1e6).toFixed(1)}M`} />
          <KvRow label="Equity committed" value={`$${(capital.equity_committed_usd / 1e6).toFixed(1)}M`} />
          <KvRow label="Equity drawn"     value={`$${(capital.equity_drawn_usd / 1e6).toFixed(1)}M`} />
        </div>
        <div>
          <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 6 }}>
            P&amp;L · MTD vs YTD
          </div>
          <KvRow label="Revenue (MTD)"  value={`$${(pnl.mtd.revenue_usd / 1e6).toFixed(2)}M`} />
          <KvRow label="EBITDA (MTD)"   value={`$${(pnl.mtd.ebitda_usd / 1e6).toFixed(2)}M`} />
          <KvRow label="Revenue (YTD)"  value={`$${(pnl.ytd.revenue_usd / 1e6).toFixed(2)}M`} />
          <KvRow label="EBITDA (YTD)"   value={`$${(pnl.ytd.ebitda_usd / 1e6).toFixed(2)}M`} />
        </div>
      </div>
    </Section>
  );
}

function KvRow({ label, value }) {
  return (
    <div style={{
      display: 'flex', justifyContent: 'space-between',
      padding: '4px 0', fontSize: 12, lineHeight: 1.45,
      borderBottom: '1px dotted var(--border-hairline)',
    }}>
      <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
      <span className="tabular" style={{ color: 'var(--text)', fontWeight: 'var(--fw-medium)' }}>{value}</span>
    </div>
  );
}

function ReceivablesBlock({ receivables }) {
  const bands = [
    { id: 'band_0_30',  label: '0–30 days',  tone: 'text' },
    { id: 'band_31_60', label: '31–60 days', tone: 'amber' },
    { id: 'band_61_90', label: '61–90 days', tone: 'amber' },
    { id: 'band_90p',   label: '90+ days',   tone: 'rust' },
  ];
  return (
    <Section
      title="Receivables ageing"
      sub={`${receivables.terms_days}-day terms · counterparty ${receivables.counterparty || 'GIBDLC'} · current book $${receivables.current_balance_usd.toLocaleString()}`}
    >
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
        <thead>
          <tr style={{ borderBottom: '1px solid var(--border-hairline)' }}>
            <th style={th}>Band</th>
            <th style={th}>Balance</th>
            <th style={th}>Share</th>
            <th style={th}>Chases</th>
          </tr>
        </thead>
        <tbody>
          {bands.map((b) => {
            const usd = receivables.ageing[b.id] || 0;
            const sharePct = (usd / receivables.current_balance_usd) * 100;
            const tone = b.tone === 'rust'  ? 'var(--bauxite-rust)'
                       : b.tone === 'amber' ? 'var(--signal-amber)'
                       : 'var(--text)';
            return (
              <tr key={b.id} style={{ borderBottom: '1px solid var(--border-hairline)' }}>
                <td style={td}>{b.label}</td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: usd > 0 ? tone : 'var(--text-tertiary)' }}>
                  ${usd.toLocaleString()}
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                  {sharePct.toFixed(1)}%
                </td>
                <td style={{ ...td, color: 'var(--text-secondary)' }}>
                  {receivables.followup_counts?.[b.id] || 0}
                </td>
              </tr>
            );
          })}
          <tr style={{ background: 'var(--surface)' }}>
            <td style={{ ...td, fontWeight: 'var(--fw-medium)' }}>Overdue (31+ days)</td>
            <td style={{ ...td, fontFamily: 'var(--font-mono)', fontWeight: 'var(--fw-medium)', color: receivables.overdue_pct >= 8 ? 'var(--bauxite-rust)' : 'var(--text)' }}>
              ${receivables.overdue_usd.toLocaleString()}
            </td>
            <td style={{ ...td, fontFamily: 'var(--font-mono)', fontWeight: 'var(--fw-medium)', color: receivables.overdue_pct >= 8 ? 'var(--bauxite-rust)' : 'var(--text)' }}>
              {receivables.overdue_pct.toFixed(1)}%
            </td>
            <td style={td}></td>
          </tr>
        </tbody>
      </table>
    </Section>
  );
}

function ForecastBlock({ forecast }) {
  const verdictTone = forecast.verdict === 'on_pace_or_above' ? STATUS_TONE.PASS
                    : forecast.verdict === 'below_floor_at_pace' ? STATUS_TONE.WATCH
                    : STATUS_TONE.BREACH;
  return (
    <Section title="Take-or-pay forecast">
      <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 24 }}>
        <div>
          <div className="tabular" style={{
            fontSize: 32, fontWeight: 'var(--fw-black)',
            color: verdictTone, lineHeight: 1.05,
          }}>
            {(forecast.projected_eom / 1000).toFixed(1)}<span style={{ fontSize: 18 }}> kt</span>
          </div>
          <div className="micro" style={{ color: 'var(--text-tertiary)', marginTop: 4 }}>
            PROJECTED EOM · {forecast.pct_of_floor.toFixed(1)}% OF FLOOR
          </div>
        </div>
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
          <div>
            <span style={{ color: 'var(--text-tertiary)' }}>Verdict</span>{' '}
            <strong style={{ color: verdictTone }}>{VERDICT_LABEL[forecast.verdict] || forecast.verdict}</strong>
          </div>
          <div>
            Floor target <span className="tabular" style={{ color: 'var(--text)' }}>{(forecast.floor_target / 1000).toFixed(1)} kt</span>
            {' · '}
            Monthly target <span className="tabular" style={{ color: 'var(--text)' }}>{(forecast.monthly_target / 1000).toFixed(1)} kt</span>
          </div>
          <div>
            Delivered <span className="tabular" style={{ color: 'var(--text)' }}>{(forecast.delivered_mtd / 1000).toFixed(1)} kt</span>
            {' over '}{forecast.days_elapsed} days · {forecast.days_remaining} remaining
          </div>
          <div>
            Daily avg <span className="tabular" style={{ color: 'var(--text)' }}>{forecast.daily_avg.toLocaleString()} t</span>
            {' · required to floor '}<span className="tabular" style={{ color: 'var(--text)' }}>{forecast.required_daily_floor.toLocaleString()} t/day</span>
          </div>
          {forecast.shortfall_to_floor > 0 ? (
            <div style={{ color: 'var(--bauxite-rust)' }}>
              Shortfall to floor: <span className="tabular">{forecast.shortfall_to_floor.toLocaleString()} t</span>
            </div>
          ) : (
            <div style={{ color: 'var(--signal-green)' }}>
              Surplus over floor: <span className="tabular">{forecast.surplus_over_floor.toLocaleString()} t</span>
            </div>
          )}
        </div>
      </div>

      {forecast.trend.length > 0 && (
        <div style={{ marginTop: 14 }}>
          <div className="micro" style={{ color: 'var(--text-tertiary)', marginBottom: 6 }}>
            Last {forecast.trend.length}-day projected EOM trend
          </div>
          <ForecastTrendChart trend={forecast.trend} floor={forecast.floor_target} />
        </div>
      )}
    </Section>
  );
}

function ForecastTrendChart({ trend, floor }) {
  const max = Math.max(...trend.map((p) => p.eom_tonnes), floor * 1.05);
  const min = Math.min(...trend.map((p) => p.eom_tonnes), floor * 0.95);
  const range = Math.max(max - min, 1);
  return (
    <div>
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${trend.length}, 1fr)`,
        alignItems: 'flex-end',
        gap: 3,
        height: 50,
        position: 'relative',
      }}>
        <div style={{
          position: 'absolute', left: 0, right: 0,
          bottom: `${((floor - min) / range) * 100}%`,
          borderTop: '1px dashed var(--bauxite-rust)',
          opacity: 0.5,
        }} />
        {trend.map((p) => {
          const heightPct = Math.max(8, ((p.eom_tonnes - min) / range) * 100);
          const tone = p.verdict === 'on_pace_or_above' ? STATUS_TONE.PASS
                     : p.verdict === 'below_floor_at_pace' ? STATUS_TONE.WATCH
                     : STATUS_TONE.BREACH;
          return (
            <div key={p.date} style={{
              height: `${heightPct}%`,
              background: tone,
              opacity: 0.85,
              borderRadius: 1,
            }} title={`${p.date}: ${(p.eom_tonnes / 1000).toFixed(1)}kt`} />
          );
        })}
      </div>
    </div>
  );
}

function HaulerRankingBlock({ haulers }) {
  return (
    <Section title="Hauler attainment ranking" sub="Active counterparties · MTD attainment vs contracted share">
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
        <thead>
          <tr style={{ borderBottom: '1px solid var(--border-hairline)' }}>
            <th style={th}>Hauler</th>
            <th style={th}>Trucks</th>
            <th style={th}>Delivered</th>
            <th style={th}>Contracted</th>
            <th style={th}>Attainment</th>
            <th style={th}>SLA</th>
          </tr>
        </thead>
        <tbody>
          {haulers.map((h) => {
            const tone = h.attainment_pct >= 80 ? STATUS_TONE.PASS
                       : h.attainment_pct >= 70 ? STATUS_TONE.WATCH
                       : STATUS_TONE.BREACH;
            return (
              <tr key={h.hauler_id} style={{ borderBottom: '1px solid var(--border-hairline)' }}>
                <td style={td}>{h.display_name}</td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                  {h.active_trucks}/{h.contracted_trucks}
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)' }}>
                  {(h.delivered_mtd / 1000).toFixed(1)} kt
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                  {(h.contracted_mtd / 1000).toFixed(1)} kt
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: tone, fontWeight: 'var(--fw-medium)' }}>
                  {h.attainment_pct.toFixed(1)}%
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                  {h.sla_attainment_pct != null ? `${h.sla_attainment_pct.toFixed(1)}%` : '—'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </Section>
  );
}

// ── Risk register — Phase 72 ──────────────────────────────────────

const RISK_TONE = {
  critical: 'var(--bauxite-rust)',
  high:     'var(--bauxite-rust)',
  medium:   'var(--signal-amber)',
  low:      'var(--text-secondary)',
};
const RISK_STATUS_LABEL = {
  open:       'Open',
  mitigating: 'Mitigating',
  monitoring: 'Monitoring',
  closed:     'Closed',
};

function RiskRegisterBlock({ risks, counts }) {
  // Phase 74 — roll-up: total mitigation steps across all open risks.
  const stepsRollup = risks.reduce((m, r) => {
    const s = r.steps_summary || { done_count: 0, total_count: 0 };
    m.done += s.done_count;
    m.total += s.total_count;
    return m;
  }, { done: 0, total: 0 });
  const sub = counts
    ? `${counts.open_count} open · ${counts.high_open_count} high or critical · ${counts.stale_count} stale (30+ days unreviewed)${stepsRollup.total > 0 ? ` · ${stepsRollup.done}/${stepsRollup.total} mitigation steps complete` : ''}`
    : '';
  return (
    <Section title="Risk register" sub={sub}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
        <thead>
          <tr style={{ borderBottom: '1px solid var(--border-hairline)' }}>
            <th style={th}>Risk</th>
            <th style={th}>Category</th>
            <th style={th}>Severity</th>
            <th style={th}>Status</th>
            <th style={th}>Owner</th>
            <th style={th}>Steps</th>
            <th style={th}>Reviewed</th>
          </tr>
        </thead>
        <tbody>
          {risks.map((r) => {
            const sevTone = RISK_TONE[r.severity] || 'var(--text)';
            const reviewedDays = r.last_reviewed_at
              ? Math.floor((Date.now() - new Date(r.last_reviewed_at).getTime()) / (24 * 60 * 60 * 1000))
              : null;
            const stale = reviewedDays == null || reviewedDays >= 30;
            return (
              <Fragment key={r.id}>
              <tr style={{ borderBottom: '1px solid var(--border-hairline)', breakInside: 'avoid' }}>
                <td style={{ ...td, borderLeft: `3px solid ${sevTone}`, paddingLeft: 10 }}>
                  <div style={{ color: 'var(--text)', fontWeight: 'var(--fw-medium)' }}>{r.title}</div>
                  {r.description && (
                    <div style={{ fontSize: 10, color: 'var(--text-secondary)', marginTop: 2, lineHeight: 1.4 }}>
                      {r.description}
                    </div>
                  )}
                  {r.mitigation_plan && (
                    <div style={{ fontSize: 10, color: 'var(--text-tertiary)', marginTop: 2, lineHeight: 1.4 }}>
                      <strong>Mitigation:</strong> {r.mitigation_plan}
                    </div>
                  )}
                </td>
                <td style={{ ...td, color: 'var(--text-secondary)', textTransform: 'capitalize' }}>{r.category}</td>
                <td style={{ ...td, color: sevTone, textTransform: 'capitalize', fontWeight: 'var(--fw-medium)' }}>
                  {r.severity}
                </td>
                <td style={{ ...td, color: 'var(--text-secondary)' }}>
                  {RISK_STATUS_LABEL[r.status] || r.status}
                </td>
                <td style={{ ...td, color: 'var(--text-secondary)' }}>
                  {r.owner || <span style={{ color: 'var(--text-tertiary)', fontStyle: 'italic' }}>unowned</span>}
                </td>
                <td style={{ ...td, fontFamily: 'var(--font-mono)' }}>
                  {(() => {
                    const s = r.steps_summary || { done_count: 0, total_count: 0 };
                    if (s.total_count === 0) {
                      return <span style={{ color: 'var(--text-tertiary)', fontStyle: 'italic' }}>none</span>;
                    }
                    const tone = s.done_count === s.total_count ? 'var(--signal-green)' : 'var(--text-secondary)';
                    return <span style={{ color: tone }}>{s.done_count}/{s.total_count}</span>;
                  })()}
                </td>
                <td style={{
                  ...td,
                  color: stale ? 'var(--bauxite-rust)' : 'var(--text-secondary)',
                  fontFamily: 'var(--font-mono)',
                }}>
                  {reviewedDays == null ? 'never' : `${reviewedDays}d ago`}
                </td>
              </tr>
              {/* Phase 77 — recent comments inline so the credit committee
                  reads the play-by-play, not just the static fields. */}
              {r.recent_comments && r.recent_comments.length > 0 && (
                <tr style={{ borderBottom: '1px solid var(--border-hairline)' }}>
                  <td colSpan={7} style={{
                    padding: '6px 12px 10px',
                    background: 'var(--surface)',
                    borderLeft: `3px solid ${sevTone}`,
                  }}>
                    <div className="micro" style={{
                      color: 'var(--text-tertiary)',
                      marginBottom: 4,
                      letterSpacing: '0.06em',
                    }}>
                      LATEST DISCUSSION · {r.comment_count} total
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                      {r.recent_comments.map((c) => (
                        <div key={c.id} style={{
                          fontSize: 11,
                          color: 'var(--text-secondary)',
                          lineHeight: 1.45,
                        }}>
                          <span style={{ color: 'var(--text)', fontWeight: 'var(--fw-medium)' }}>
                            {c.author?.display_name ?? 'Unknown'}
                          </span>
                          <span style={{ color: 'var(--text-tertiary)' }}>
                            {' · '}
                            {new Date(c.created_at).toLocaleDateString('en-GB', {
                              day: '2-digit', month: 'short', timeZone: 'UTC',
                            })}
                          </span>
                          <span style={{ marginLeft: 6 }}>{c.body}</span>
                        </div>
                      ))}
                    </div>
                  </td>
                </tr>
              )}
              </Fragment>
            );
          })}
        </tbody>
      </table>
    </Section>
  );
}

function OpenAlertsBlock({ alerts }) {
  return (
    <Section title="Open critical & warning alerts" sub={`${alerts.length} open · lender-relevant slice`}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {alerts.map((a) => {
          const tone = a.severity === 'CRITICAL' ? 'var(--bauxite-rust)' : 'var(--signal-amber)';
          return (
            <div key={a.id} style={{
              padding: '8px 12px',
              background: 'var(--surface)',
              borderRadius: 'var(--radius-sm)',
              borderLeft: `3px solid ${tone}`,
              fontSize: 12,
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 2 }}>
                <span style={{ color: 'var(--text)', fontWeight: 'var(--fw-medium)' }}>{a.title}</span>
                <span className="mono" style={{ fontSize: 10, color: tone, letterSpacing: '0.06em' }}>
                  {a.severity} · {a.status}
                </span>
              </div>
              <div style={{ color: 'var(--text-secondary)', fontSize: 11, lineHeight: 1.4 }}>
                {a.body}
              </div>
            </div>
          );
        })}
      </div>
    </Section>
  );
}

function Footer({ data }) {
  const docId = `LP-${data.period.start.slice(0, 10).replace(/-/g, '')}-${data.generated_at.slice(11, 16).replace(':', '')}`;
  return (
    <footer style={{
      marginTop: 32, paddingTop: 12,
      borderTop: '1px solid var(--border-hairline)',
      fontSize: 10, color: 'var(--text-tertiary)',
      display: 'flex', justifyContent: 'space-between',
    }}>
      <span className="mono">Document {docId}</span>
      <span>AXIS Command Center · NewCo Logistics JV Ltd · Composed live from corridor state</span>
    </footer>
  );
}

// ── Style constants ───────────────────────────────────────────────

const th = {
  textAlign: 'left',
  padding: '6px 8px',
  fontSize: 10,
  letterSpacing: '0.06em',
  textTransform: 'uppercase',
  color: 'var(--text-tertiary)',
  fontWeight: 500,
};
const td = {
  padding: '6px 8px',
  fontSize: 12,
  color: 'var(--text)',
  lineHeight: 1.5,
};
