/*
 * TodayDigest — printable end-of-day briefing (Phase 40).
 *
 * A standalone page (no app sidebar/topbar) that the operator opens
 * in a new tab and Cmd-P's. The same /api/today/digest payload that
 * powers it could later feed an emailable PDF or a regulator export.
 *
 * Sections, top to bottom:
 *   1. Letterhead   — AXIS / corridor masthead, period, generated by
 *   2. Corridor KPIs — tonnes vs floor, fleet, on-time
 *   3. Dominant story — same headline the cockpit highlighted today
 *   4. Open follow-ups — action items still pending (carry to tomorrow)
 *   5. Auto-cleared — alerts the lifecycle remediated, with reason
 *   6. Operations log — full audit trail of writes since UTC start of day
 *   7. Hauler split — per-hauler activity table
 *   8. Filings posture — regulatory window
 *   9. Footer — signature line, generated_at, doc id
 *
 * Print rules: every section honours `break-inside: avoid` so a row
 * doesn't get cleaved across pages; the letterhead repeats on each
 * page via @media print + position:running (Chrome supports the
 * simpler version we use here without margin boxes).
 */

import { useEffect, useState } from 'react';
import { authFetch } from '../lib/auth';

const ENTITY_LABEL = {
  hse_incident:     'HSE incident',
  licence:          'Licence',
  filing:           'Filing',
  workorder:        'Workorder',
  coaching_session: 'Coaching',
  alert:            'Alert',
  hauler:           'Hauler',
  integration:      'Integration',
  report:           'Report',
};

export default function TodayDigest() {
  const [data, setData]   = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    document.body.classList.add('digest-mode');
    document.title = 'AXIS · Daily digest';
    (async () => {
      try {
        const res = await authFetch('/api/today/digest');
        if (res.status === 403) {
          setError('Daily digest is restricted for your role.');
          return;
        }
        if (!res.ok) throw new Error(`digest ${res.status}`);
        setData(await res.json());
      } catch (err) { setError(err.message); }
    })();
    return () => { document.body.classList.remove('digest-mode'); };
  }, []);

  if (error) return <Frame><p style={{ color: 'var(--bauxite-rust)' }}>{error}</p></Frame>;
  if (!data) return <Frame><p style={{ color: 'var(--text-tertiary)' }}>Composing digest…</p></Frame>;

  return (
    <Frame>
      <PrintBar />
      <Letterhead data={data} />
      <CorridorKPIs corridor={data.corridor} />
      <Section title="Dominant story">
        <p style={{ margin: 0, fontSize: 14, lineHeight: 1.5 }}>
          <strong>{data.dominant_story?.headline}</strong>
          {data.dominant_story?.body && (
            <>{' '}<span style={{ color: 'var(--text-secondary)' }}>{data.dominant_story.body}</span></>
          )}
        </p>
      </Section>

      {data.forecast && <ForecastSection forecast={data.forecast} />}

      <Section title={`Open follow-ups · ${data.open_action_items?.length ?? 0}`}>
        {(data.open_action_items?.length ?? 0) === 0 ? (
          <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic' }}>
            No pending follow-ups — the desk closed clean.
          </p>
        ) : (
          <ol style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.55 }}>
            {data.open_action_items.map((it) => (
              <li key={it.id} style={{ marginBottom: 4 }}>
                <span style={{
                  display: 'inline-block',
                  fontSize: 9,
                  letterSpacing: '0.06em',
                  textTransform: 'uppercase',
                  padding: '1px 6px',
                  marginRight: 8,
                  border: '1px solid currentColor',
                  borderRadius: 3,
                  color: it.priority === 'high' ? 'var(--bauxite-rust)' : 'var(--signal-amber)',
                }}>
                  {it.priority}
                </span>
                {it.body}
              </li>
            ))}
          </ol>
        )}
      </Section>

      {(data.auto_cleared?.length ?? 0) > 0 && (
        <Section title={`Auto-cleared by lifecycle · ${data.auto_cleared.length}`}>
          <ul style={{ margin: 0, padding: 0, listStyle: 'none', fontSize: 12 }}>
            {data.auto_cleared.map((a) => (
              <li key={a.id} style={{
                padding: '6px 0',
                borderBottom: '1px solid var(--border-hairline)',
              }}>
                <div style={{ color: 'var(--text)' }}>
                  <strong>{a.title}</strong>
                  {a.hauler_id && <span style={{ color: 'var(--text-tertiary)' }}> · {a.hauler_id}</span>}
                </div>
                <div style={{ color: 'var(--text-secondary)', marginTop: 2 }}>
                  {a.cleared_by?.reason}
                  {a.cleared_by?.actor && (
                    <span style={{ color: 'var(--text-tertiary)' }}>
                      {' · '}{a.cleared_by.actor}
                    </span>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Section>
      )}

      <OperationsLog log={data.operations_log} />
      <HaulerSplit haulers={data.haulers} projections={data.forecast?.haulers} />
      <FilingsPosture posture={data.filings_posture} />
      <Observations items={data.observations} />

      <Footer data={data} />
    </Frame>
  );
}

// ── Layout shell ───────────────────────────────────────────────────

function Frame({ children }) {
  return (
    <div style={{
      maxWidth: 820,
      margin: '0 auto',
      padding: '32px 36px 64px',
      background: 'var(--bone, #f5f1e8)',
      color: 'var(--text)',
      fontFamily: 'var(--font-body, system-ui)',
      minHeight: '100vh',
    }}>
      {children}
    </div>
  );
}

function PrintBar() {
  return (
    <div className="no-print" style={{
      display: 'flex',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
      paddingBottom: 12,
      borderBottom: '1px dashed var(--border-hairline)',
      fontSize: 12,
      color: 'var(--text-tertiary)',
    }}>
      <span>Cmd-P / Ctrl-P to save as PDF</span>
      <button
        type="button"
        onClick={() => window.print()}
        style={{
          padding: '6px 14px',
          background: 'var(--bauxite-rust)',
          color: 'var(--bone)',
          border: 'none',
          borderRadius: 4,
          fontSize: 12,
          fontFamily: 'inherit',
          letterSpacing: '0.04em',
          cursor: 'pointer',
        }}
      >
        Print
      </button>
    </div>
  );
}

function Letterhead({ data }) {
  const day = data.period?.since?.slice(0, 10);
  return (
    <header style={{
      borderBottom: '2px solid var(--text)',
      paddingBottom: 16,
      marginBottom: 20,
    }}>
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
      }}>
        <div>
          <div style={{
            fontSize: 24,
            fontWeight: 600,
            letterSpacing: '0.02em',
          }}>
            AXIS
          </div>
          <div style={{
            fontSize: 11,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: 'var(--text-secondary)',
            marginTop: 2,
          }}>
            {data.corridor?.name} · {data.corridor?.length_km} km
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{
            fontSize: 11,
            letterSpacing: '0.16em',
            textTransform: 'uppercase',
            color: 'var(--text-secondary)',
          }}>
            Daily digest
          </div>
          <div className="mono tabular" style={{
            fontSize: 14,
            color: 'var(--text)',
            marginTop: 2,
          }}>
            {day}
          </div>
        </div>
      </div>
      <div style={{
        fontSize: 11,
        color: 'var(--text-tertiary)',
        marginTop: 12,
        display: 'flex',
        gap: 18,
        flexWrap: 'wrap',
      }}>
        <span>Counterparty <strong style={{ color: 'var(--text-secondary)' }}>{data.corridor?.counterparty}</strong></span>
        <span>Generated by <strong style={{ color: 'var(--text-secondary)' }}>{data.generated_by?.display_name}</strong> · {data.generated_by?.organisation}</span>
        <span>at <span className="mono">{fmtTime(data.generated_at)} UTC</span></span>
      </div>
    </header>
  );
}

// ── Sections ──────────────────────────────────────────────────────

function Section({ title, children }) {
  return (
    <section style={{
      marginBottom: 22,
      breakInside: 'avoid',
    }}>
      <h2 style={{
        margin: 0,
        marginBottom: 8,
        paddingBottom: 4,
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        color: 'var(--bauxite-rust)',
        borderBottom: '1px solid var(--border-hairline)',
        fontWeight: 500,
      }}>
        {title}
      </h2>
      {children}
    </section>
  );
}

function CorridorKPIs({ corridor }) {
  if (!corridor) return null;
  const deliveredPct = corridor.tonnes_contracted_mtd > 0
    ? (corridor.tonnes_delivered_mtd / corridor.tonnes_contracted_mtd) * 100
    : 0;
  const floorPct = corridor.take_or_pay_floor_pct * 100;
  return (
    <Section title="Corridor posture · MTD">
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
        gap: 12,
      }}>
        <Kpi
          label="Tonnes delivered"
          value={`${(corridor.tonnes_delivered_mtd / 1000).toFixed(1)} kt`}
          sub={`of ${(corridor.tonnes_contracted_mtd / 1000).toFixed(1)} kt · ${deliveredPct.toFixed(1)}%`}
          tone={deliveredPct >= floorPct ? 'green' : 'rust'}
        />
        <Kpi
          label="Take-or-pay floor"
          value={`${floorPct.toFixed(0)}%`}
          sub={`Run-rate ${deliveredPct.toFixed(1)}%`}
          tone={deliveredPct >= floorPct ? 'green' : 'rust'}
        />
        <Kpi
          label="Active trucks"
          value={`${corridor.active_trucks_today}`}
          sub={`of ${corridor.contracted_trucks} contracted`}
        />
        <Kpi
          label="On-time SLA"
          value={`${corridor.sla_attainment_pct?.toFixed?.(1) ?? '—'}%`}
        />
      </div>
    </Section>
  );
}

// Phase 42 — Take-or-pay forecast block for the digest. Same content
// as the on-screen card but rendered with print-safe units (no rust
// gradients, plain backgrounds). Kept terse: projected EOM, the gap
// to floor, the daily lift required, and the top-3 idle-truck levers.
function ForecastSection({ forecast }) {
  const f = forecast;
  const verdictLabel = {
    on_pace_for_contracted: 'On pace for contracted',
    above_floor:            'Above floor, below contracted',
    banked_floor_drift:     'Floor banked — pace slipping',
    below_floor_at_pace:    'Below floor at current pace',
  }[f.projection.verdict] ?? '—';
  const verdictTone =
    f.projection.verdict === 'on_pace_for_contracted' ? 'green' :
    f.projection.verdict === 'below_floor_at_pace'    ? 'rust'  :
    f.projection.verdict === 'banked_floor_drift'     ? 'amber' : null;
  return (
    <Section title="Take-or-pay forecast · month-end">
      <div style={{ marginBottom: 8, fontSize: 12, color: 'var(--text-secondary)' }}>
        {f.horizon.days_elapsed}/{f.horizon.days_in_month} days elapsed ·{' '}
        <strong style={{
          color: verdictTone === 'rust'  ? 'var(--bauxite-rust)'
               : verdictTone === 'green' ? 'var(--signal-green)'
               : verdictTone === 'amber' ? 'var(--signal-amber)'
               : 'var(--text)',
        }}>{verdictLabel}</strong>
      </div>
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
        gap: 12,
        marginBottom: 8,
      }}>
        <Kpi
          label="Projected EOM"
          value={`${(f.projection.eom_tonnes / 1000).toFixed(1)} kt`}
          sub={`${f.projection.pct_of_floor}% of floor`}
          tone={f.projection.shortfall_to_floor > 0 ? 'rust' : 'green'}
        />
        <Kpi
          label="Floor target"
          value={`${(f.targets.floor / 1000).toFixed(1)} kt`}
          sub={`${(f.targets.floor_pct * 100).toFixed(0)}% of nameplate`}
        />
        <Kpi
          label="Required daily"
          value={f.required.daily_to_floor > 0 ? `${f.required.daily_to_floor.toLocaleString()} t/d` : 'Cleared'}
          sub={
            f.required.lift_pct_to_floor != null && f.required.lift_pct_to_floor > 0
              ? `+${f.required.lift_pct_to_floor.toFixed(1)}% on current pace`
              : `vs ${f.actual.daily_avg.toLocaleString()} t/d actual`
          }
          tone={f.required.daily_to_floor > f.actual.daily_avg ? 'rust' : null}
        />
        <Kpi
          label={f.projection.shortfall_to_floor > 0 ? 'Shortfall to floor' : 'Surplus over floor'}
          value={`${(f.projection.shortfall_to_floor || f.projection.surplus_over_floor).toLocaleString()} t`}
          sub={`over ${f.horizon.days_remaining} d remaining`}
          tone={f.projection.shortfall_to_floor > 0 ? 'rust' : 'green'}
        />
      </div>

      {f.workshop_drag && f.workshop_drag.open_count > 0 && (
        <div style={{ marginTop: 8, marginBottom: 8 }}>
          <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 4 }}>
            Workshop drag · <strong>{f.workshop_drag.open_count}</strong> open work
            order{f.workshop_drag.open_count === 1 ? '' : 's'} costing{' '}
            <strong>{f.workshop_drag.total_drag.toLocaleString()} t</strong> over
            the month
            {f.workshop_drag.pct_of_floor_gap != null && f.workshop_drag.pct_of_floor_gap > 0 && (
              <> ({f.workshop_drag.pct_of_floor_gap.toFixed(0)}% of floor gap)</>
            )}
          </div>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border-hairline)', color: 'var(--text-tertiary)' }}>
                <th style={{ textAlign: 'left',  padding: '4px 8px' }}>Rig</th>
                <th style={{ textAlign: 'left',  padding: '4px 8px' }}>Workorder</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Days open</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Lost so far</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Total drag</th>
              </tr>
            </thead>
            <tbody>
              {f.workshop_drag.by_workorder.slice(0, 5).map((w) => (
                <tr key={w.workorder_id} style={{ borderBottom: '1px solid var(--border-hairline)', breakInside: 'avoid' }}>
                  <td style={{ padding: '4px 8px', fontFamily: 'var(--font-mono)' }}>{w.rig_id}</td>
                  <td style={{ padding: '4px 8px' }}>{w.title}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right' }}>{w.days_open.toFixed(1)}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right' }}>{w.lost_so_far.toLocaleString()}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', color: 'var(--bauxite-rust)', fontWeight: 600 }}>
                    {w.total_drag.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {f.projection.shortfall_to_floor > 0 && f.levers.by_hauler.length > 0 && (
        <div style={{ marginTop: 8 }}>
          <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 4 }}>
            Idle-truck levers · activating all recovers{' '}
            <strong>{f.levers.total_remainder_recovery_if_all_active.toLocaleString()} t</strong>
            {f.levers.pct_of_floor_gap_closed != null && (
              <> ({f.levers.pct_of_floor_gap_closed.toFixed(0)}% of gap)</>
            )}
          </div>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border-hairline)', color: 'var(--text-tertiary)' }}>
                <th style={{ textAlign: 'left',  padding: '4px 8px' }}>Hauler</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Active / Contracted</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Idle</th>
                <th style={{ textAlign: 'right', padding: '4px 8px' }}>Recoverable t</th>
              </tr>
            </thead>
            <tbody>
              {f.levers.by_hauler.slice(0, 5).map((l) => (
                <tr key={l.hauler_id} style={{ borderBottom: '1px solid var(--border-hairline)', breakInside: 'avoid' }}>
                  <td style={{ padding: '4px 8px' }}>{l.display_name}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right' }}>{l.active_trucks} / {l.contracted_trucks}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right', color: 'var(--bauxite-rust)' }}>{l.idle_trucks}</td>
                  <td style={{ padding: '4px 8px', textAlign: 'right' }}>+{l.remainder_recovery.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Section>
  );
}

function Kpi({ label, value, sub, tone }) {
  const color = tone === 'rust'  ? 'var(--bauxite-rust)'
             : tone === 'green' ? 'var(--signal-green)'
             : 'var(--text)';
  return (
    <div style={{
      padding: '10px 12px',
      background: 'var(--surface-raised, #fff)',
      border: '1px solid var(--border-hairline)',
      borderRadius: 4,
    }}>
      <div style={{
        fontSize: 9,
        letterSpacing: '0.14em',
        textTransform: 'uppercase',
        color: 'var(--text-tertiary)',
      }}>
        {label}
      </div>
      <div className="tabular" style={{
        fontSize: 22,
        fontWeight: 500,
        color,
        marginTop: 4,
        lineHeight: 1.1,
      }}>
        {value}
      </div>
      {sub && (
        <div style={{
          fontSize: 10,
          color: 'var(--text-tertiary)',
          marginTop: 2,
        }}>
          {sub}
        </div>
      )}
    </div>
  );
}

function OperationsLog({ log }) {
  if (!log) return null;
  const { counts = {}, entries = [] } = log;
  const subtitle = `${counts.writes ?? 0} write${counts.writes === 1 ? '' : 's'}` +
    ` · ${counts.auto_cleared ?? 0} alert${counts.auto_cleared === 1 ? '' : 's'} auto-cleared` +
    (counts.by_type ? ` · ${Object.entries(counts.by_type).map(([k, v]) => `${v} ${ENTITY_LABEL[k] ?? k}`).join(', ')}` : '');

  return (
    <Section title="Operations log · today">
      <p style={{
        margin: '0 0 8px 0',
        fontSize: 11,
        color: 'var(--text-secondary)',
      }}>
        {subtitle}
      </p>
      {entries.length === 0 ? (
        <p style={{ margin: 0, color: 'var(--text-tertiary)', fontStyle: 'italic', fontSize: 12 }}>
          No corridor write activity recorded today.
        </p>
      ) : (
        <table style={{
          width: '100%',
          borderCollapse: 'collapse',
          fontSize: 11,
        }}>
          <thead>
            <tr style={{ color: 'var(--text-tertiary)', textAlign: 'left' }}>
              <th style={th()}>Time</th>
              <th style={th()}>Entity</th>
              <th style={th()}>Action</th>
              <th style={{ ...th(), width: '50%' }}>Summary</th>
              <th style={th()}>Actor</th>
            </tr>
          </thead>
          <tbody>
            {entries.map((e) => (
              <tr key={e.id} style={{
                borderTop: '1px solid var(--border-hairline)',
                breakInside: 'avoid',
              }}>
                <td className="mono" style={td()}>{fmtTime(e.ts)}</td>
                <td style={td()}>{ENTITY_LABEL[e.entity_type] ?? e.entity_type}</td>
                <td className="mono" style={{ ...td(), textTransform: 'uppercase', fontSize: 10, color: 'var(--text-secondary)' }}>{e.action}</td>
                <td style={td()}>{e.summary}</td>
                <td style={{ ...td(), color: 'var(--text-secondary)' }}>{e.actor?.display_name ?? '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </Section>
  );
}

function HaulerSplit({ haulers, projections }) {
  if (!haulers?.length) return null;
  // Phase 44 — keyed lookup so each hauler row carries its month-end
  // projection alongside the MTD actuals. Lets the digest reader
  // compare "where you are now" with "where you'll land" in one row.
  const projByHauler = (projections ?? []).reduce((m, p) => {
    m[p.hauler_id] = p; return m;
  }, {});
  const verdictTone = (v) => v === 'on_pace'           ? 'var(--signal-green)'
                          : v === 'severely_lagging'   ? 'var(--bauxite-rust)'
                          : v === 'lagging'            ? 'var(--signal-amber)'
                          : 'var(--text)';
  return (
    <Section title="Hauler split · MTD vs projected EOM">
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
        <thead>
          <tr style={{ color: 'var(--text-tertiary)', textAlign: 'left' }}>
            <th style={th()}>Hauler</th>
            <th style={{ ...th(), textAlign: 'right' }}>Tonnes MTD</th>
            <th style={{ ...th(), textAlign: 'right' }}>Projected EOM</th>
            <th style={{ ...th(), textAlign: 'right' }}>vs Contracted</th>
            <th style={{ ...th(), textAlign: 'right' }}>Active / Contracted</th>
            <th style={{ ...th(), textAlign: 'right' }}>On-time</th>
            <th style={{ ...th(), textAlign: 'right' }}>Status</th>
          </tr>
        </thead>
        <tbody>
          {haulers.map((h) => {
            const p = projByHauler[h.id];
            const tone = p ? verdictTone(p.verdict) : 'var(--text-tertiary)';
            return (
              <tr key={h.id} style={{ borderTop: '1px solid var(--border-hairline)', breakInside: 'avoid' }}>
                <td style={td()}>{h.display_name}</td>
                <td className="tabular" style={{ ...td(), textAlign: 'right' }}>
                  {h.tonnes_mtd?.toLocaleString?.() ?? h.tonnes_mtd ?? '—'}
                </td>
                <td className="tabular" style={{ ...td(), textAlign: 'right', color: tone }}>
                  {p && h.status === 'active' ? p.projected_eom.toLocaleString() : '—'}
                </td>
                <td className="tabular" style={{ ...td(), textAlign: 'right', color: tone, fontWeight: p && p.verdict !== 'on_pace' ? 600 : 400 }}>
                  {p && h.status === 'active' ? `${p.projected_pct_contracted.toFixed(0)}%` : '—'}
                </td>
                <td className="tabular" style={{ ...td(), textAlign: 'right' }}>{h.active_trucks} / {h.contracted_trucks}</td>
                <td className="tabular" style={{ ...td(), textAlign: 'right' }}>{h.on_time_pct?.toFixed?.(1) ?? '—'}%</td>
                <td className="mono" style={{ ...td(), textAlign: 'right', fontSize: 10, textTransform: 'uppercase', color: h.status === 'active' ? 'var(--signal-green)' : 'var(--text-tertiary)' }}>{h.status}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </Section>
  );
}

function FilingsPosture({ posture }) {
  if (!posture) return null;
  return (
    <Section title="Regulatory filings posture">
      <div style={{
        display: 'flex',
        gap: 18,
        fontSize: 12,
        marginBottom: 8,
        flexWrap: 'wrap',
      }}>
        <span><strong>{posture.filed}</strong> / {posture.total} filed</span>
        {posture.overdue > 0 && (
          <span style={{ color: 'var(--bauxite-rust)' }}><strong>{posture.overdue}</strong> overdue</span>
        )}
        {posture.due_in_3d > 0 && (
          <span style={{ color: 'var(--signal-amber)' }}><strong>{posture.due_in_3d}</strong> due ≤ 3d</span>
        )}
      </div>
      {(posture.upcoming?.length ?? 0) > 0 && (
        <ul style={{ margin: 0, padding: 0, listStyle: 'none', fontSize: 11 }}>
          {posture.upcoming.map((f) => (
            <li key={f.id} style={{
              padding: '4px 0',
              borderTop: '1px solid var(--border-hairline)',
              display: 'flex',
              justifyContent: 'space-between',
              gap: 12,
            }}>
              <span><strong>{f.agency}</strong> — {f.detail?.split('·')?.[0]?.trim?.() ?? f.detail}</span>
              <span className="mono" style={{ color: 'var(--text-tertiary)' }}>due {f.due}</span>
            </li>
          ))}
        </ul>
      )}
    </Section>
  );
}

function Observations({ items }) {
  if (!items?.length) return null;
  return (
    <Section title={`Observations · ${items.length}`}>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', fontSize: 12 }}>
        {items.map((o, i) => (
          <li key={o.id ?? i} style={{
            padding: '5px 0',
            borderBottom: '1px solid var(--border-hairline)',
            color: 'var(--text-secondary)',
          }}>
            {o.body || o.headline || o.summary}
          </li>
        ))}
      </ul>
    </Section>
  );
}

function Footer({ data }) {
  return (
    <footer style={{
      marginTop: 28,
      paddingTop: 12,
      borderTop: '1px solid var(--border-hairline)',
      fontSize: 10,
      color: 'var(--text-tertiary)',
      display: 'flex',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 12,
    }}>
      <span>
        AXIS Command Center · NewCo Logistics JV Ltd. · NYINAHIN — TAKORADI bauxite haulage
      </span>
      <span className="mono">
        digest · {data.generated_at}
      </span>
    </footer>
  );
}

// ── Helpers ───────────────────────────────────────────────────────

function th() {
  return {
    padding: '6px 8px',
    fontWeight: 500,
    fontSize: 10,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  };
}

function td() {
  return { padding: '6px 8px', verticalAlign: 'top' };
}

function fmtTime(iso) {
  if (!iso) return '—';
  return iso.slice(11, 16);
}
